2022-09-09 20:38:18.562 | INFO     | __main__:main:31 - Process started at : 2022-09-09 20:38:18.554787
2022-09-09 20:38:18.562 | INFO     | __main__:main:32 - -------------------------------------------------------
2022-09-09 20:38:18.562 | INFO     | __main__:main:34 - ============== SECTION - 1 : DB CONNECTION ==============
2022-09-09 20:38:18.601 | INFO     | __main__:main:40 -  > DB Connection successful.
2022-09-09 20:38:18.602 | INFO     | __main__:main:43 - ============== SECTION - 2 : GETTING SITE INFO ==============
2022-09-09 20:38:23.777 | INFO     | __main__:main:48 - > Found 23 sites from database table configs.
2022-09-09 20:38:23.778 | INFO     | __main__:main:49 - > Successfully extracted site info from database.
2022-09-09 20:38:23.778 | INFO     | __main__:main:52 - ============== SECTION - 3 : LOCAL FILES IO ==============
2022-09-09 20:38:23.792 | INFO     | __main__:main:58 - > Found 566 NETCDF files in the local directory /Users/vasu/Library/CloudStorage/OneDrive-DecisionTreeAnalyticsServices/TensorDynamics/Data/Satellite.
2022-09-09 20:39:57.263 | INFO     | __main__:main:81 - > Found 39595 NETCDF files in the DB Table td_satellite.nwc_satellite.
2022-09-09 20:39:57.264 | INFO     | __main__:main:84 - > Found 25 sites ['Barod', None, 'Siddipet', 'Rawra', 'Kamuthi', 'NJV_Delhi', 'Sadla', 'Parli', 'MSEDCL', 'Kavithal', 'Hero Power', 'Jhansi', 'Chhattisgarh', 'Kanasar', 'Lahori', 'Gunga', 'SITE3', 'SECI-1', 'Badnawar', 'Muktainagar', 'Ichhawar', 'SITE2', 'SITE1', 'Bitta', 'SITE4'] in the DB Table td_satellite.nwc_satellite.
2022-09-09 20:39:57.264 | ERROR    | src.funcs.decorators:dec_inner:47 - An error has been caught in function 'dec_inner', process 'MainProcess' (1777), thread 'MainThread' (8629999104):
Traceback (most recent call last):

  File "/Users/vasu/Library/CloudStorage/OneDrive-DecisionTreeAnalyticsServices/TensorDynamics/Codebases/TD-Satellite/main_data_read.py", line 113, in <module>
    main()
    └ <function main at 0x7fa5810dd5e0>

> File "/Users/vasu/Library/CloudStorage/OneDrive-DecisionTreeAnalyticsServices/TensorDynamics/Codebases/TD-Satellite/src/funcs/decorators.py", line 47, in dec_inner
    rv = func(*args, **kwargs)
         │     │       └ {}
         │     └ ()
         └ <function main at 0x7fa5810dd310>

  File "/Users/vasu/Library/CloudStorage/OneDrive-DecisionTreeAnalyticsServices/TensorDynamics/Codebases/TD-Satellite/main_data_read.py", line 87, in main
    for site, files in site_file_map:
                       └ {'Badnawar': ['S_NWC_CT_MSG1_IODC-VISIR_20210201T000000Z.nc', 'S_NWC_CT_MSG1_IODC-VISIR_20210201T001500Z.nc', 'S_NWC_CT_MSG1_...

ValueError: too many values to unpack (expected 2)
